
################################################################################
###### This file is used to simulate "fake data" for public use, ###############
###### as the data used in the paper cannot be made publicly available #########
###### and its use is meant to be restricted to reproducibility review #########
################################################################################


### The "fake data" is generated by taking each patient observed in the overall "real dataset"
### and assigning them to a random new hospital

set.seed(1234)

load("forReview/RSCdataObject.Rdata")

### We reorganize data into data.frame form first

   sub.data.frames<-lapply(1:length(full.out[[5]]),function(i) {
       covariate.table<-full.out[[5]][i]*full.out[[1]][,i]
       full<-unlist(sapply(1:length(covariate.table),function(j) rep(names(covariate.table)[j],covariate.table[j])))
       fac<-rep(i,length(full))
       out<-data.frame(full,fac)
       return(out)
     })

   data<-Reduce(f=rbind,x=sub.data.frames)
   data$fac<-as.factor(data$fac)

### Now we randomize patients into hospitals

reassign<-sample(1:151,151)                                     ### Begin by randomly renaming each hospital
new.facs<-reassign[as.integer(data$fac)]      

new.facs<-new.facs+floor(rnorm(nrow(data),sd=1))                ### Have every patient go to a random hospital "next door"
new.facs[new.facs>151]<-ceiling(runif(sum(new.facs>151))*151)   ### Some patients might to a non-existent hospital this way, 
new.facs[new.facs<1]<-ceiling(runif(sum(new.facs<1))*151)       ### have them got to a random hospital

data$new.facs<-new.facs

### Now we determine if each patient received a high dose
### We want to do this in a way such that P(Y|X) remains (roughly) the same
###   even in the fake data, so that the fake data is still realistic
###   in the context of CT scan radiation
### We also want to make sure the hospitals still have a good
###   variety of performance qualities

hospital.danger<-1/full.out[[2]]    ## assign each hospital a "danger" value

  
distribute.highs<-function(x){
  
  subdata<-data[data$full==levels(data$full)[x],]
  to.distribute<-round(full.out[[4]][x]*nrow(subdata)) ## (about) how many high doses should be in this group?
  
  are.over<-rep(0,length(levels(data$fac)))            ## we'll give "high dosers" to each hospital
                                                       ## initialize no one has any
  
  for(pat in 1:to.distribute){                         ## for each high-dose patient
    
    is.full<-(as.numeric(table(subdata$fac))-are.over)!=0                  ## check which hospital still "have room"
    hospital.prob<-(hospital.danger*is.full)/sum(hospital.danger*is.full)  ## have chance of being "given to"
                                                                           ## a hospital based on their "danger" and
                                                                           ## whether it has room
    
    to.hospital<-which(c(rmultinom(n=1,size=1,prob=hospital.prob))==1)     ## to which hospital?
    are.over[to.hospital]<-are.over[to.hospital]+1
  }
  
  are.not.over<-as.numeric(table(subdata$fac)-are.over)                ## how many in each hospital don't have high doses
  
  out<-unlist(sapply(1:length(are.over), function(j) c(rep(1,are.over[j]),rep(0,are.not.over[j])))) 
                        ## is each patient high dose
  return(out)
}


distributed.highs<-lapply(1:length(levels(data$full)),distribute.highs)
data<-data[order(data$full),]
data$dlp.over<-unlist(distributed.highs)                               ## make patients high dose

new.1<-sapply(1:151,function(i) table(data$full[data$new.facs==i])[levels(data$full)]/nrow(data[data$new.facs==i,]))
new.2<-tapply(data$dlp.over,data$new.facs,mean)
new.4<-tapply(data$dlp.over,data$full,mean)
new.5<-c(table(data$new.facs))


full.out[[1]]<-new.1
full.out[[2]]<-new.2
full.out[[4]]<-new.4
full.out[[5]]<-new.5


save(full.out,file="forPublic/RSCdataObject.Rdata")








